apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::531891198544:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GK3OY3ZDMWL8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::531891198544:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-13T02:16:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2237"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0bddb3d7-d2d8-45b5-8943-6a159691bc94
